from __future__ import annotations

# Area name == top-level package under md_generator == skill id suffix.
AREA_SKILL_IDS: dict[str, str] = {
    "global": "mdengine-ai-global",
    "reference": "mdengine-reference",
    "archive": "mdengine-ai-archive",
    "codeflow": "mdengine-ai-codeflow",
    "db": "mdengine-ai-db",
    "graph": "mdengine-ai-graph",
    "image": "mdengine-ai-image",
    "media": "mdengine-ai-media",
    "openapi": "mdengine-ai-openapi",
    "pdf": "mdengine-ai-pdf",
    "playwright": "mdengine-ai-playwright",
    "ppt": "mdengine-ai-ppt",
    "text": "mdengine-ai-text",
    "url": "mdengine-ai-url",
    "word": "mdengine-ai-word",
    "xlsx": "mdengine-ai-xlsx",
}

# keyword (lowercase match) -> areas; priority higher wins when sorting candidates
_KEYWORD_SPECS: list[tuple[str, list[str], int]] = [
    ("archive", ["archive"], 100),
    ("zip", ["archive"], 90),
    ("md-zip", ["archive"], 95),
    ("codeflow", ["codeflow"], 100),
    ("md-codeflow", ["codeflow"], 100),
    ("architecture", ["codeflow"], 40),
    ("db", ["db"], 100),
    ("sql", ["db"], 85),
    ("erd", ["db"], 80),
    ("mongo", ["db"], 80),
    ("md-db", ["db"], 95),
    ("graph", ["graph"], 100),
    ("neo4j", ["graph"], 95),
    ("networkx", ["graph"], 85),
    ("md-graph", ["graph"], 95),
    ("image", ["image"], 100),
    ("ocr", ["image"], 90),
    ("tesseract", ["image"], 85),
    ("md-image", ["image"], 95),
    ("media", ["media"], 100),
    ("audio", ["media"], 95),
    ("video", ["media"], 95),
    ("youtube", ["media"], 95),
    ("whisper", ["media"], 85),
    ("md-audio", ["media"], 90),
    ("md-video", ["media"], 90),
    ("openapi", ["openapi"], 100),
    ("swagger", ["openapi"], 90),
    ("md-openapi", ["openapi"], 95),
    ("pdf", ["pdf"], 100),
    ("pymupdf", ["pdf"], 80),
    ("md-pdf", ["pdf"], 95),
    ("playwright", ["playwright"], 100),
    ("spa", ["playwright"], 50),
    ("headless", ["playwright"], 45),
    ("md-playwright", ["playwright"], 95),
    ("ppt", ["ppt"], 100),
    ("pptx", ["ppt"], 95),
    ("powerpoint", ["ppt"], 90),
    ("md-ppt", ["ppt"], 95),
    ("text", ["text"], 100),
    ("json", ["text"], 70),
    ("xml", ["text"], 70),
    ("md-text", ["text"], 95),
    ("url", ["url"], 100),
    ("html", ["url"], 75),
    ("readability", ["url"], 60),
    ("md-url", ["url"], 95),
    ("word", ["word"], 100),
    ("docx", ["word"], 95),
    ("mammoth", ["word"], 70),
    ("md-word", ["word"], 95),
    ("xlsx", ["xlsx"], 100),
    ("excel", ["xlsx"], 90),
    ("csv", ["xlsx"], 75),
    ("md-xlsx", ["xlsx"], 95),
    ("mcp", ["db", "graph", "openapi", "media", "playwright"], 30),
    ("fastapi", ["db", "graph", "openapi", "media", "playwright", "codeflow"], 25),
    ("install", ["global"], 20),
    ("extras", ["global"], 20),
    ("pip", ["global"], 15),
]


def build_routing_block() -> dict:
    keyword_routing = [
        {"keyword": k, "areas": areas, "priority": p} for k, areas, p in _KEYWORD_SPECS
    ]
    return {
        "globalSkillFile": "skills/global-skill.md",
        "dependencyGraphFile": "dependency-graph.json",
        "moduleSkillId": dict(AREA_SKILL_IDS),
        "keywordRouting": keyword_routing,
    }
